# Generated by Django 5.2.4 on 2025-07-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='universities.universityprofile'),
        ),
        migrations.AddField(
            model_name='agendastaffassignment',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='appointments.agenda'),
        ),
        migrations.AddField(
            model_name='agendastaffassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentstatistics',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentstatistics',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='universities.universityprofile'),
        ),
        migrations.AddField(
            model_name='appointmentstatistics',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='appointments.appointmenttheme'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='appointments.appointmenttheme'),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to='appointments.agenda'),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.calendarslot'),
        ),
        migrations.AddField(
            model_name='emailreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='talenteligibilitycriteria',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='appointments.agenda'),
        ),
        migrations.AlterUniqueTogether(
            name='agendastaffassignment',
            unique_together={('agenda', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentstatistics',
            unique_together={('university', 'theme', 'staff', 'date')},
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='calendarslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='calendarslot',
            constraint=models.CheckConstraint(condition=models.Q(('current_bookings__lte', models.F('max_capacity'))), name='valid_capacity'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarslot',
            unique_together={('agenda', 'staff', 'slot_date', 'start_time')},
        ),
    ]
