# Generated by Django 5.2.4 on 2025-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time when the object was last updated.')),
                ('display_name', models.CharField(max_length=100)),
                ('current_task_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
