# Generated by Django 5.2.4 on 2025-07-13 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='universitystaff',
            unique_together={('user', 'university')},
        ),
    ]
