# Generated by Django 5.2.4 on 2025-07-13 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agendas', to='universities.universitystaff'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='universities.university'),
        ),
        migrations.AddField(
            model_name='agendastaffassignment',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='appointments.agenda'),
        ),
        migrations.AddField(
            model_name='agendastaffassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_assignments', to='universities.universitystaff'),
        ),
    ]
